version: '3.4'

services:  
  app_demo_nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - 8081:80
    networks:
      - app_demo
  
  app1:
    build: .
    environment:
      - APP_NAME=localhost1    
    networks:
      - app_demo
    hostname: app1
  
  app2:
    build: .
    environment:
      - APP_NAME=localhost2
    networks:
      - app_demo  
    hostname: app2
      
networks:
  app_demo:
    driver: bridge